---
nexus_user: nexus
nexus_group: nexus
nexus_version: "3.83.1-03"
nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-linux-x86_64.tar.gz"
nexus_install_parent: /opt
nexus_install_dir: /opt/nexus
nexus_work_dir: /opt/sonatype-work
nexus_port: 8081
nexus_service_name: nexus
nexus_min_heap: 1200m
nexus_max_heap: 1200m
