---
sonarqube_user: sonar
sonarqube_group: sonar
sonarqube_version: "10.6.0.92116"
sonarqube_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
sonarqube_install_parent: /opt
sonarqube_install_dir: "/opt/sonarqube-{{ sonarqube_version }}"
sonarqube_current_link: /opt/sonarqube
sonarqube_port: 9000
sonarqube_db_name: sonarqube
sonarqube_db_user: sonar
sonarqube_db_password: "ChangeMeSonarDbPassword123!"
sonarqube_jdbc_url: "jdbc:postgresql://localhost:5432/{{ sonarqube_db_name }}"
sonarqube_service_name: sonarqube
sonarqube_web_context: /
